// AUTO-GENERATED from seed.sql — default content used by the offline store
// (when Supabase is NOT configured) and to seed a fresh Supabase database.
// Regenerate: see scripts/gen-seed.py

export const SEED = {
  "settings": {
    "site_name": "Vijayavyuham",
    "tagline_en": "Strategy • Intelligence • Impact",
    "tagline_te": "వ్యూహం • విశ్లేషణ • ప్రభావం",
    "tagline_hi": "रणनीति • बुद्धिमत्ता • प्रभाव",
    "contact_phone": "",
    "contact_whatsapp": "",
    "contact_email": "",
    "contact_address_en": "Hyderabad, Telangana, India",
    "contact_address_te": "హైదరాబాద్, తెలంగాణ, భారతదేశం",
    "contact_address_hi": "हैदराबाद, तेलंगाना, भारत",
    "social_facebook": "",
    "social_instagram": "",
    "social_whatsapp": "",
    "social_twitter": "",
    "social_youtube": "",
    "page_home": 1,
    "page_about": 1,
    "page_services": 1,
    "page_blog": 1,
    "page_contact": 1,
    "page_gallery": 0,
    "page_team": 0,
    "meta_description_en": "Vijayavyuham is a data-driven political campaign consultancy serving Telangana and Andhra Pradesh. Voter research, booth management, social media campaigns, IVR, WhatsApp outreach, and AI video messaging.",
    "meta_keywords": "political consultancy Telangana, election campaign management Andhra Pradesh, voter survey Telugu states, booth management, political survey research, Vijayavyuham",
    "hero_headline_en": "Win with Strategy. Lead with Intelligence.",
    "hero_headline_te": "వ్యూహంతో గెలవండి. విశ్లేషణతో నడిపించండి.",
    "hero_headline_hi": "रणनीति से जीतें। बुद्धिमत्ता से नेतृत्व करें।",
    "hero_subtext_en": "A modern political campaign partner for the Telugu states — turning voter insight into decisive electoral action across Telangana and Andhra Pradesh.",
    "hero_subtext_te": "తెలుగు రాష్ట్రాల కోసం ఆధునిక రాజకీయ ప్రచార భాగస్వామి — తెలంగాణ మరియు ఆంధ్రప్రదేశ్‌లలో ఓటర్ల అవగాహనను నిర్ణయాత్మక ఎన్నికల చర్యగా మారుస్తాము.",
    "hero_subtext_hi": "तेलुगु राज्यों के लिए एक आधुनिक राजनीतिक अभियान भागीदार — तेलंगाना और आंध्र प्रदेश में मतदाता अंतर्दृष्टि को निर्णायक चुनावी कार्रवाई में बदलना।",
    "about_body_en": "Vijayavyuham is a new-generation political strategy firm built for the Telugu states. We combine rigorous ground research, sharp data analysis, and disciplined field execution into one connected campaign system. Every recommendation we make is grounded in evidence — never guesswork. Our focus is simple: understand the voter deeply, communicate with clarity, and execute on the ground with precision so our clients can make confident decisions at every stage of the campaign.",
    "about_body_te": "విజయవ్యూహం అనేది తెలుగు రాష్ట్రాల కోసం రూపొందించబడిన కొత్త తరం రాజకీయ వ్యూహ సంస్థ. మేము కఠినమైన క్షేత్రస్థాయి పరిశోధన, పదునైన డేటా విశ్లేషణ మరియు క్రమశిక్షణతో కూడిన క్షేత్ర అమలును ఒకే అనుసంధాన ప్రచార వ్యవస్థగా మిళితం చేస్తాము. మా ప్రతి సిఫార్సు ఆధారాలపై ఆధారపడి ఉంటుంది — ఎప్పుడూ ఊహలపై కాదు.",
    "about_body_hi": "विजयव्यूहम तेलुगु राज्यों के लिए बनाई गई एक नई पीढ़ी की राजनीतिक रणनीति फर्म है। हम कठोर जमीनी शोध, तेज डेटा विश्लेषण और अनुशासित क्षेत्र निष्पादन को एक जुड़े हुए अभियान प्रणाली में जोड़ते हैं। हमारी हर सिफारिश साक्ष्य पर आधारित होती है — कभी अनुमान पर नहीं।",
    "mission_en": "To empower political leaders and organizations in the Telugu states with clear, evidence-led strategy and flawless ground execution.",
    "mission_te": "స్పష్టమైన, ఆధారాధారిత వ్యూహం మరియు దోషరహిత క్షేత్ర అమలుతో తెలుగు రాష్ట్రాల్లోని రాజకీయ నాయకులు మరియు సంస్థలను శక్తివంతం చేయడం.",
    "mission_hi": "तेलुगु राज्यों में राजनीतिक नेताओं और संगठनों को स्पष्ट, साक्ष्य-आधारित रणनीति और त्रुटिहीन क्षेत्र निष्पादन के साथ सशक्त बनाना।",
    "vision_en": "To become the most trusted political campaign partner in Telangana and Andhra Pradesh — known for integrity, intelligence, and impact.",
    "vision_te": "తెలంగాణ మరియు ఆంధ్రప్రదేశ్‌లలో అత్యంత నమ్మకమైన రాజకీయ ప్రచార భాగస్వామిగా మారడం — నిజాయితీ, విశ్లేషణ మరియు ప్రభావం కోసం గుర్తింపు పొందడం.",
    "vision_hi": "तेलंगाना और आंध्र प्रदेश में सबसे भरोसेमंद राजनीतिक अभियान भागीदार बनना — ईमानदारी, बुद्धिमत्ता और प्रभाव के लिए जाना जाने वाला।"
  },
  "services": [
    {
      "id": 1,
      "slug": "political-survey-research",
      "sort_order": 1,
      "icon": "fa-magnifying-glass-chart",
      "title_en": "Political Survey & Research",
      "short_en": "Measure voter sentiment, local issues, leadership perception, and electoral movement through structured political research.",
      "description_en": "We design and run structured political research to measure voter sentiment, surface local issues, gauge leadership perception, and track electoral movement over time. Our surveys are built for the ground realities of Telangana and Andhra Pradesh — sampling that reflects real constituencies, questionnaires in Telugu, and analysis you can act on. Research before rhetoric, always.",
      "title_te": "రాజకీయ సర్వే & పరిశోధన",
      "short_te": "నిర్మాణాత్మక రాజకీయ పరిశోధన ద్వారా ఓటర్ల మనోభావాలు, స్థానిక సమస్యలు మరియు నాయకత్వ అవగాహనను కొలవండి.",
      "description_te": "",
      "title_hi": "राजनीतिक सर्वेक्षण और अनुसंधान",
      "short_hi": "संरचित राजनीतिक अनुसंधान के माध्यम से मतदाता भावना, स्थानीय मुद्दों और नेतृत्व धारणा को मापें।",
      "description_hi": "",
      "features": "[{\"en\":\"Research before rhetoric\",\"te\":\"వాదన కంటే ముందు పరిశోధన\",\"hi\":\"बयानबाजी से पहले शोध\"},{\"en\":\"Constituency-first understanding\",\"te\":\"నియోజకవర్గం ఆధారిత అవగాహన\",\"hi\":\"निर्वाचन क्षेत्र-प्रथम समझ\"},{\"en\":\"Evidence-led strategy\",\"te\":\"ఆధారాధారిత వ్యూహం\",\"hi\":\"साक्ष्य-आधारित रणनीति\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    },
    {
      "id": 2,
      "slug": "voter-mapping",
      "sort_order": 2,
      "icon": "fa-map-location-dot",
      "title_en": "Voter Mapping",
      "short_en": "Organize constituencies by booth, locality, voter segment, persuasion opportunity, and turnout risk.",
      "description_en": "We map your constituency down to the booth and locality — segmenting voters by community, persuasion opportunity, and turnout risk. This gives your campaign a clear picture of where to invest energy, which segments to prioritize, and where the real battlegrounds lie. Map before movement.",
      "title_te": "ఓటర్ మ్యాపింగ్",
      "short_te": "బూత్, ప్రాంతం, ఓటర్ విభాగం మరియు హాజరు ప్రమాదం ద్వారా నియోజకవర్గాలను నిర్వహించండి.",
      "description_te": "",
      "title_hi": "मतदाता मानचित्रण",
      "short_hi": "बूथ, इलाके, मतदाता वर्ग और मतदान जोखिम के आधार पर निर्वाचन क्षेत्रों को व्यवस्थित करें।",
      "description_hi": "",
      "features": "[{\"en\":\"Map before movement\",\"te\":\"కదలిక కంటే ముందు మ్యాపింగ్\",\"hi\":\"आंदोलन से पहले मानचित्रण\"},{\"en\":\"Segmented voter understanding\",\"te\":\"విభజిత ఓటర్ అవగాహన\",\"hi\":\"खंडित मतदाता समझ\"},{\"en\":\"Priority outreach zones\",\"te\":\"ప్రాధాన్యత ప్రచార ప్రాంతాలు\",\"hi\":\"प्राथमिकता आउटरीच क्षेत्र\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    },
    {
      "id": 3,
      "slug": "social-media-campaign",
      "sort_order": 3,
      "icon": "fa-hashtag",
      "title_en": "Social Media Political Campaign Management",
      "short_en": "Plan platform strategy, content, rapid response, audience engagement, and performance-led digital communication.",
      "description_en": "We run daily narrative control across every platform — planning platform strategy, producing creative political content, managing rapid response, and driving audience engagement with performance-led digital communication tuned for Telugu audiences.",
      "title_te": "సోషల్ మీడియా రాజకీయ ప్రచార నిర్వహణ",
      "short_te": "ప్లాట్‌ఫారమ్ వ్యూహం, కంటెంట్, వేగవంతమైన స్పందన మరియు ప్రేక్షకుల నిమగ్నతను ప్లాన్ చేయండి.",
      "description_te": "",
      "title_hi": "सोशल मीडिया राजनीतिक अभियान प्रबंधन",
      "short_hi": "प्लेटफ़ॉर्म रणनीति, सामग्री, त्वरित प्रतिक्रिया और दर्शक जुड़ाव की योजना बनाएं।",
      "description_hi": "",
      "features": "[{\"en\":\"Daily narrative control\",\"te\":\"రోజువారీ కథన నియంత్రణ\",\"hi\":\"दैनिक कथा नियंत्रण\"},{\"en\":\"Creative political communication\",\"te\":\"సృజనాత్మక రాజకీయ సమాచారం\",\"hi\":\"रचनात्मक राजनीतिक संचार\"},{\"en\":\"Platform-ready execution\",\"te\":\"ప్లాట్‌ఫారమ్-సిద్ధ అమలు\",\"hi\":\"प्लेटफ़ॉर्म-तैयार निष्पादन\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    },
    {
      "id": 4,
      "slug": "booth-management",
      "sort_order": 4,
      "icon": "fa-people-group",
      "title_en": "Election Booth Management",
      "short_en": "Booth-first execution with local accountability and review-led field work for maximum turnout.",
      "description_en": "Elections are won booth by booth. We build booth-first execution systems with clear local accountability, structured review cycles, and disciplined field work so no polling booth is left unmanaged on the day that matters most.",
      "title_te": "ఎన్నికల బూత్ నిర్వహణ",
      "short_te": "స్థానిక జవాబుదారీతనం మరియు సమీక్ష ఆధారిత క్షేత్ర పనితో బూత్-ఆధారిత అమలు.",
      "description_te": "",
      "title_hi": "चुनाव बूथ प्रबंधन",
      "short_hi": "स्थानीय जवाबदेही और समीक्षा-आधारित क्षेत्र कार्य के साथ बूथ-प्रथम निष्पादन।",
      "description_hi": "",
      "features": "[{\"en\":\"Booth-first execution\",\"te\":\"బూత్-ఆధారిత అమలు\",\"hi\":\"बूथ-प्रथम निष्पादन\"},{\"en\":\"Local accountability\",\"te\":\"స్థానిక జవాబుదారీతనం\",\"hi\":\"स्थानीय जवाबदेही\"},{\"en\":\"Review-led field work\",\"te\":\"సమీక్ష ఆధారిత క్షేత్ర పని\",\"hi\":\"समीक्षा-आधारित क्षेत्र कार्य\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    },
    {
      "id": 5,
      "slug": "rally-yatra-management",
      "sort_order": 5,
      "icon": "fa-route",
      "title_en": "Rally & Yatra Management",
      "short_en": "Coordinate routes, crowds, local mobilization, media moments, logistics, and post-event campaign follow-up.",
      "description_en": "From route planning to crowd coordination, local mobilization, media moments, and full logistics — we manage rallies and yatras end to end, and follow up after every event to convert momentum into lasting campaign gains. Movement with message.",
      "title_te": "ర్యాలీ & యాత్ర నిర్వహణ",
      "short_te": "మార్గాలు, జనసమూహాలు, స్థానిక సమీకరణ, మీడియా క్షణాలు మరియు లాజిస్టిక్స్‌ను సమన్వయం చేయండి.",
      "description_te": "",
      "title_hi": "रैली और यात्रा प्रबंधन",
      "short_hi": "मार्ग, भीड़, स्थानीय लामबंदी, मीडिया क्षण और लॉजिस्टिक्स का समन्वय करें।",
      "description_hi": "",
      "features": "[{\"en\":\"Movement with message\",\"te\":\"సందేశంతో కూడిన కదలిక\",\"hi\":\"संदेश के साथ आंदोलन\"},{\"en\":\"Route-led visibility\",\"te\":\"మార్గ ఆధారిత దృశ్యమానత\",\"hi\":\"मार्ग-आधारित दृश्यता\"},{\"en\":\"Crowd & media coordination\",\"te\":\"జనసమూహం & మీడియా సమన్వయం\",\"hi\":\"भीड़ और मीडिया समन्वय\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    },
    {
      "id": 6,
      "slug": "event-management",
      "sort_order": 6,
      "icon": "fa-calendar-check",
      "title_en": "Event Management",
      "short_en": "Deliver political meetings, public programs, stakeholder events, and campaign activations with disciplined coordination.",
      "description_en": "We deliver political meetings, public programs, stakeholder gatherings, and campaign activations with disciplined coordination — every detail planned, every message aligned, every event built to advance the campaign.",
      "title_te": "ఈవెంట్ నిర్వహణ",
      "short_te": "రాజకీయ సమావేశాలు, ప్రజా కార్యక్రమాలు మరియు ప్రచార కార్యక్రమాలను క్రమశిక్షణతో అందించండి.",
      "description_te": "",
      "title_hi": "कार्यक्रम प्रबंधन",
      "short_hi": "राजनीतिक बैठकें, सार्वजनिक कार्यक्रम और अभियान सक्रियण को अनुशासित समन्वय के साथ प्रदान करें।",
      "description_hi": "",
      "features": "[{\"en\":\"Organized public engagement\",\"te\":\"వ్యవస్థీకృత ప్రజా నిమగ్నత\",\"hi\":\"संगठित सार्वजनिक जुड़ाव\"},{\"en\":\"Campaign-ready event design\",\"te\":\"ప్రచార-సిద్ధ ఈవెంట్ డిజైన్\",\"hi\":\"अभियान-तैयार कार्यक्रम डिज़ाइन\"},{\"en\":\"Message-led execution\",\"te\":\"సందేశ ఆధారిత అమలు\",\"hi\":\"संदेश-आधारित निष्पादन\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    },
    {
      "id": 7,
      "slug": "ivr-bulk-calls",
      "sort_order": 7,
      "icon": "fa-phone-volume",
      "title_en": "IVR Bulk Calls",
      "short_en": "Reach large voter groups with recorded voice messages, language targeting, scheduling, and response tracking.",
      "description_en": "Reach lakhs of voters with recorded voice messages in Telugu, Hindi, or English. We handle language targeting, scheduling, and response tracking so your campaign message lands at scale with measurable feedback.",
      "title_te": "IVR బల్క్ కాల్స్",
      "short_te": "రికార్డ్ చేసిన వాయిస్ సందేశాలతో పెద్ద ఓటర్ సమూహాలను చేరుకోండి.",
      "description_te": "",
      "title_hi": "IVR बल्क कॉल",
      "short_hi": "रिकॉर्ड किए गए वॉयस संदेशों के साथ बड़े मतदाता समूहों तक पहुंचें।",
      "description_hi": "",
      "features": "[{\"en\":\"Recorded voter outreach\",\"te\":\"రికార్డ్ చేసిన ఓటర్ ప్రచారం\",\"hi\":\"रिकॉर्ड किया गया मतदाता आउटरीच\"},{\"en\":\"Rapid constituency coverage\",\"te\":\"వేగవంతమైన నియోజకవర్గ కవరేజ్\",\"hi\":\"तीव्र निर्वाचन क्षेत्र कवरेज\"},{\"en\":\"Campaign-ready call flows\",\"te\":\"ప్రచార-సిద్ధ కాల్ ప్రవాహాలు\",\"hi\":\"अभियान-तैयार कॉल फ्लो\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    },
    {
      "id": 8,
      "slug": "whatsapp-bulk-messaging",
      "sort_order": 8,
      "icon": "fa-whatsapp",
      "title_en": "WhatsApp Bulk Messaging",
      "short_en": "Distribute campaign updates, local messages, invitations, and media assets through organized WhatsApp outreach.",
      "description_en": "Distribute campaign updates, localized messages, event invitations, and rich media through organized WhatsApp outreach — the platform where Telugu voters actually spend their time. Direct, personal, and trackable.",
      "title_te": "వాట్సాప్ బల్క్ మెసేజింగ్",
      "short_te": "వ్యవస్థీకృత వాట్సాప్ ద్వారా ప్రచార నవీకరణలు మరియు మీడియాను పంపిణీ చేయండి.",
      "description_te": "",
      "title_hi": "व्हाट्सएप बल्क मैसेजिंग",
      "short_hi": "संगठित व्हाट्सएप के माध्यम से अभियान अपडेट और मीडिया वितरित करें।",
      "description_hi": "",
      "features": "[{\"en\":\"Direct campaign updates\",\"te\":\"ప్రత్యక్ష ప్రచార నవీకరణలు\",\"hi\":\"प्रत्यक्ष अभियान अपडेट\"},{\"en\":\"Localized message distribution\",\"te\":\"స్థానికీకృత సందేశ పంపిణీ\",\"hi\":\"स्थानीयकृत संदेश वितरण\"},{\"en\":\"Volunteer network support\",\"te\":\"వాలంటీర్ నెట్‌వర్క్ మద్దతు\",\"hi\":\"स्वयंसेवक नेटवर्क समर्थन\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    },
    {
      "id": 9,
      "slug": "ai-video-messaging",
      "sort_order": 9,
      "icon": "fa-clapperboard",
      "title_en": "AI Personalised Video Messaging",
      "short_en": "Create personalized leader videos at scale for constituencies, communities, supporters, and campaign milestones.",
      "description_en": "Create personalized leader videos at scale — addressing constituencies, communities, and supporters by name and locality. AI-driven video outreach that feels one-to-one, delivered at campaign scale.",
      "title_te": "AI వ్యక్తిగతీకృత వీడియో మెసేజింగ్",
      "short_te": "నియోజకవర్గాలు మరియు మద్దతుదారుల కోసం వ్యక్తిగతీకృత నాయకుడి వీడియోలను సృష్టించండి.",
      "description_te": "",
      "title_hi": "AI व्यक्तिगत वीडियो संदेश",
      "short_hi": "निर्वाचन क्षेत्रों और समर्थकों के लिए व्यक्तिगत नेता वीडियो बनाएं।",
      "description_hi": "",
      "features": "[{\"en\":\"Personalized voter communication\",\"te\":\"వ్యక్తిగతీకృత ఓటర్ సమాచారం\",\"hi\":\"व्यक्तिगत मतदाता संचार\"},{\"en\":\"Scalable video outreach\",\"te\":\"స్కేలబుల్ వీడియో ప్రచారం\",\"hi\":\"स्केलेबल वीडियो आउटरीच\"},{\"en\":\"Leader-led messaging\",\"te\":\"నాయకుడి ఆధారిత సందేశం\",\"hi\":\"नेता-आधारित संदेश\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    },
    {
      "id": 10,
      "slug": "opinion-exit-poll",
      "sort_order": 10,
      "icon": "fa-square-poll-vertical",
      "title_en": "Opinion and Exit Poll",
      "short_en": "Track electoral preference, issue salience, candidate strength, and voting patterns through rigorous polling.",
      "description_en": "Track electoral preference, issue salience, candidate strength, and emerging voting patterns through methodologically rigorous opinion and exit polls — designed and analyzed specifically for the Telugu electorate.",
      "title_te": "అభిప్రాయ & ఎగ్జిట్ పోల్",
      "short_te": "కఠినమైన పోలింగ్ ద్వారా ఎన్నికల ప్రాధాన్యత మరియు ఓటింగ్ నమూనాలను ట్రాక్ చేయండి.",
      "description_te": "",
      "title_hi": "राय और एग्जिट पोल",
      "short_hi": "कठोर मतदान के माध्यम से चुनावी प्राथमिकता और मतदान पैटर्न को ट्रैक करें।",
      "description_hi": "",
      "features": "[{\"en\":\"Rigorous methodology\",\"te\":\"కఠినమైన పద్దతి\",\"hi\":\"कठोर पद्धति\"},{\"en\":\"Candidate strength tracking\",\"te\":\"అభ్యర్థి బలం ట్రాకింగ్\",\"hi\":\"उम्मीदवार ताकत ट्रैकिंग\"},{\"en\":\"Voting pattern analysis\",\"te\":\"ఓటింగ్ నమూనా విశ్లేషణ\",\"hi\":\"मतदान पैटर्न विश्लेषण\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    },
    {
      "id": 11,
      "slug": "political-advertising",
      "sort_order": 11,
      "icon": "fa-bullhorn",
      "title_en": "Political Advertising",
      "short_en": "Develop message-led creative and media campaigns for public visibility, persuasion, and voter recall.",
      "description_en": "We develop message-led creative and place it across the right media mix — building public visibility, driving persuasion, and maximizing voter recall through advertising built for the Telugu media landscape.",
      "title_te": "రాజకీయ ప్రకటనలు",
      "short_te": "ప్రజా దృశ్యమానత మరియు ఒప్పింపు కోసం సందేశ ఆధారిత సృజనాత్మక ప్రచారాలను అభివృద్ధి చేయండి.",
      "description_te": "",
      "title_hi": "राजनीतिक विज्ञापन",
      "short_hi": "सार्वजनिक दृश्यता और अनुनय के लिए संदेश-आधारित रचनात्मक अभियान विकसित करें।",
      "description_hi": "",
      "features": "[{\"en\":\"Message-led creative\",\"te\":\"సందేశ ఆధారిత సృజనాత్మకత\",\"hi\":\"संदेश-आधारित रचनात्मकता\"},{\"en\":\"Right media mix\",\"te\":\"సరైన మీడియా మిశ్రమం\",\"hi\":\"सही मीडिया मिश्रण\"},{\"en\":\"Maximized voter recall\",\"te\":\"గరిష్ట ఓటర్ రీకాల్\",\"hi\":\"अधिकतम मतदाता स्मरण\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    },
    {
      "id": 12,
      "slug": "political-canvassing",
      "sort_order": 12,
      "icon": "fa-clipboard-list",
      "title_en": "Political Canvassing",
      "short_en": "Run structured voter-contact programs that capture feedback, identify support, and strengthen local presence.",
      "description_en": "Run structured voter-contact programs that capture real feedback, identify committed support, and steadily strengthen your local presence — turning conversations into campaign intelligence.",
      "title_te": "రాజకీయ కాన్వాసింగ్",
      "short_te": "అభిప్రాయాన్ని సేకరించే మరియు మద్దతును గుర్తించే నిర్మాణాత్మక ఓటర్-సంపర్క కార్యక్రమాలను నిర్వహించండి.",
      "description_te": "",
      "title_hi": "राजनीतिक कैनवासिंग",
      "short_hi": "संरचित मतदाता-संपर्क कार्यक्रम चलाएं जो प्रतिक्रिया एकत्र करें और समर्थन की पहचान करें।",
      "description_hi": "",
      "features": "[{\"en\":\"Structured voter contact\",\"te\":\"నిర్మాణాత్మక ఓటర్ సంపర్కం\",\"hi\":\"संरचित मतदाता संपर्क\"},{\"en\":\"Feedback capture\",\"te\":\"అభిప్రాయ సేకరణ\",\"hi\":\"प्रतिक्रिया संग्रह\"},{\"en\":\"Support identification\",\"te\":\"మద్దతు గుర్తింపు\",\"hi\":\"समर्थन पहचान\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    },
    {
      "id": 13,
      "slug": "door-to-door-campaign",
      "sort_order": 13,
      "icon": "fa-house-user",
      "title_en": "Door-to-Door Campaign",
      "short_en": "Plan household outreach, volunteer deployment, voter conversations, data capture, and follow-up action.",
      "description_en": "The most personal form of politics. We plan household outreach, deploy and train volunteers, structure voter conversations, capture data at the doorstep, and drive disciplined follow-up action — building trust one home at a time.",
      "title_te": "ఇంటింటి ప్రచారం",
      "short_te": "గృహ ప్రచారం, వాలంటీర్ల నియామకం, ఓటర్ సంభాషణలు మరియు డేటా సేకరణను ప్లాన్ చేయండి.",
      "description_te": "",
      "title_hi": "घर-घर अभियान",
      "short_hi": "घरेलू आउटरीच, स्वयंसेवक तैनाती, मतदाता बातचीत और डेटा संग्रह की योजना बनाएं।",
      "description_hi": "",
      "features": "[{\"en\":\"Household outreach planning\",\"te\":\"గృహ ప్రచార ప్రణాళిక\",\"hi\":\"घरेलू आउटरीच योजना\"},{\"en\":\"Volunteer deployment\",\"te\":\"వాలంటీర్ నియామకం\",\"hi\":\"स्वयंसेवक तैनाती\"},{\"en\":\"Doorstep data capture\",\"te\":\"గుమ్మం వద్ద డేటా సేకరణ\",\"hi\":\"द्वार पर डेटा संग्रह\"}]",
      "image_url": null,
      "media_url": null,
      "is_active": 1
    }
  ],
  "testimonials": [
    {
      "id": 1,
      "author_name": "Campaign Coordinator",
      "author_role": "Assembly Constituency, Telangana",
      "photo_url": null,
      "sort_order": 1,
      "quote_en": "The clarity of their booth-level research changed how we allocated our ground teams. Every rupee spent felt intentional.",
      "quote_te": "వారి బూత్-స్థాయి పరిశోధన స్పష్టత మా క్షేత్ర బృందాలను కేటాయించే విధానాన్ని మార్చింది.",
      "quote_hi": "उनके बूथ-स्तरीय शोध की स्पष्टता ने बदल दिया कि हमने अपनी जमीनी टीमों को कैसे आवंटित किया।",
      "is_active": 1
    },
    {
      "id": 2,
      "author_name": "Local Leader",
      "author_role": "Andhra Pradesh",
      "photo_url": null,
      "sort_order": 2,
      "quote_en": "What impressed me was the discipline — every plan had evidence behind it, and every promise was delivered on the ground.",
      "quote_te": "నన్ను ఆకట్టుకున్నది క్రమశిక్షణ — ప్రతి ప్రణాళిక వెనుక ఆధారం ఉంది.",
      "quote_hi": "मुझे जो प्रभावित किया वह अनुशासन था — हर योजना के पीछे सबूत था।",
      "is_active": 1
    }
  ],
  "blogs": [
    {
      "id": 1,
      "slug": "why-data-driven-campaigns-win-in-telangana-andhra",
      "category": "Strategy",
      "cover_image": null,
      "author": "Vijayavyuham Team",
      "title_en": "Why Data-Driven Campaigns Win in Telangana & Andhra Pradesh",
      "excerpt_en": "In the Telugu states, elections are increasingly decided at the booth level. Here is why grounded voter research beats gut instinct every single time.",
      "content_en": "For decades, campaigns in Telangana and Andhra Pradesh relied heavily on the instinct of local leaders and the reach of a few dominant voices. That era is ending. Today, the constituencies of the Telugu states are among the most digitally connected and politically aware in India — and the campaigns that win are the ones that understand their voters with precision.\n\nData-driven campaigning starts with a simple discipline: research before rhetoric. Before a single slogan is written or a rally is planned, a serious campaign must know what its voters actually think. What are the top three local issues in each mandal? How is the leadership perceived among first-time voters versus older cohorts? Which booths are safe, which are swing, and which are at genuine risk of low turnout?\n\nAt Vijayavyuham, every recommendation we make begins with structured field research designed for the ground realities of the Telugu states — sampling that reflects real constituencies, questionnaires in Telugu, and analysis you can act on the same week. When you combine that intelligence with disciplined booth-level execution, you stop guessing and start winning.\n\nThe parties and leaders who embrace this shift will define the next decade of politics in Telangana and Andhra Pradesh. The ones who do not will keep spending energy in the wrong places.",
      "title_te": "తెలంగాణ & ఆంధ్రప్రదేశ్‌లో డేటా ఆధారిత ప్రచారాలు ఎందుకు గెలుస్తాయి",
      "excerpt_te": "తెలుగు రాష్ట్రాల్లో ఎన్నికలు క్రమంగా బూత్ స్థాయిలో నిర్ణయించబడుతున్నాయి. ఆధారాధారిత ఓటర్ పరిశోధన ఎందుకు ఊహల కంటే మెరుగైనదో ఇక్కడ ఉంది.",
      "content_te": "దశాబ్దాలుగా, తెలంగాణ మరియు ఆంధ్రప్రదేశ్‌లలో ప్రచారాలు స్థానిక నాయకుల ఊహలపై ఎక్కువగా ఆధారపడ్డాయి. ఆ యుగం ముగుస్తోంది. నేడు, తెలుగు రాష్ట్రాల నియోజకవర్గాలు భారతదేశంలోనే అత్యంత డిజిటల్‌గా అనుసంధానించబడిన మరియు రాజకీయంగా అవగాహన కలిగినవి.\n\nడేటా ఆధారిత ప్రచారం ఒక సరళమైన క్రమశిక్షణతో ప్రారంభమవుతుంది: వాదన కంటే ముందు పరిశోధన. ఒక్క నినాదం రాయకముందే, తీవ్రమైన ప్రచారం తన ఓటర్లు నిజంగా ఏమనుకుంటున్నారో తెలుసుకోవాలి.\n\nవిజయవ్యూహంలో, మేము చేసే ప్రతి సిఫార్సు తెలుగు రాష్ట్రాల క్షేత్రస్థాయి వాస్తవాల కోసం రూపొందించబడిన నిర్మాణాత్మక క్షేత్ర పరిశోధనతో ప్రారంభమవుతుంది.",
      "title_hi": "तेलंगाना और आंध्र प्रदेश में डेटा-संचालित अभियान क्यों जीतते हैं",
      "excerpt_hi": "तेलुगु राज्यों में चुनाव तेजी से बूथ स्तर पर तय हो रहे हैं। यहां बताया गया है कि जमीनी मतदाता अनुसंधान हर बार अंतर्ज्ञान को क्यों हराता है।",
      "content_hi": "दशकों तक, तेलंगाना और आंध्र प्रदेश में अभियान स्थानीय नेताओं के अंतर्ज्ञान पर बहुत अधिक निर्भर थे। वह युग समाप्त हो रहा है। आज, तेलुगु राज्यों के निर्वाचन क्षेत्र भारत में सबसे अधिक डिजिटल रूप से जुड़े हुए हैं।\n\nडेटा-संचालित अभियान एक सरल अनुशासन से शुरू होता है: बयानबाजी से पहले शोध। विजयव्यूहम में, हमारी हर सिफारिश तेलुगु राज्यों की जमीनी वास्तविकताओं के लिए डिज़ाइन किए गए संरचित क्षेत्र अनुसंधान से शुरू होती है।",
      "meta_title": "Why Data-Driven Political Campaigns Win in Telangana & Andhra Pradesh | Vijayavyuham",
      "meta_description": "Discover why data-driven political campaigns and booth-level voter research consistently win elections in Telangana and Andhra Pradesh. Insights from Vijayavyuham.",
      "keywords": "data driven political campaign Telangana, voter research Andhra Pradesh, booth level strategy, election consultancy Telugu states, Vijayavyuham",
      "is_published": 1,
      "published_at": "2025-11-10 09:00:00"
    },
    {
      "id": 2,
      "slug": "booth-level-strategy-guide-telugu-states",
      "category": "Field Operations",
      "cover_image": null,
      "author": "Vijayavyuham Team",
      "title_en": "The Booth-Level Strategy Guide for Winning Telugu Constituencies",
      "excerpt_en": "Elections are won and lost booth by booth. A practical look at how booth management, local accountability, and turnout planning decide close races.",
      "content_en": "Ask any experienced campaign manager in the Telugu states where elections are truly won, and the answer is always the same: at the booth. A constituency is not one big battle — it is hundreds of small ones, each with its own community mix, its own local issues, and its own turnout dynamics.\n\nBooth-first execution means treating every polling booth as a unit of accountability. Who is responsible for it? What is the expected turnout? Which households are supporters, which are undecided, and which need a follow-up conversation? Without answers to these questions, even the most charismatic candidate is flying blind on polling day.\n\nA disciplined booth management system has three pillars. First, mapping: segmenting each booth by community, persuasion opportunity, and turnout risk. Second, accountability: assigning a named local worker to each booth with clear review cycles. Third, follow-through: converting doorstep conversations into data, and data into action.\n\nAt Vijayavyuham, we build these systems from the ground up for constituencies across Telangana and Andhra Pradesh. The result is a campaign that knows exactly where to invest its energy in the final, decisive weeks.",
      "title_te": "తెలుగు నియోజకవర్గాలను గెలవడానికి బూత్-స్థాయి వ్యూహ మార్గదర్శి",
      "excerpt_te": "ఎన్నికలు బూత్ ద్వారా బూత్ గెలవబడతాయి మరియు ఓడిపోతాయి. బూత్ నిర్వహణ దగ్గరి పోటీలను ఎలా నిర్ణయిస్తుందో ఆచరణాత్మక విశ్లేషణ.",
      "content_te": "తెలుగు రాష్ట్రాల్లో ఎన్నికలు నిజంగా ఎక్కడ గెలవబడతాయో అనుభవజ్ఞుడైన ఏ ప్రచార నిర్వాహకుడిని అడిగినా, సమాధానం ఎప్పుడూ ఒకటే: బూత్ వద్ద. ఒక నియోజకవర్గం ఒక పెద్ద యుద్ధం కాదు — ఇది వందల చిన్న యుద్ధాలు.\n\nబూత్-ఆధారిత అమలు అంటే ప్రతి పోలింగ్ బూత్‌ను జవాబుదారీతన యూనిట్‌గా పరిగణించడం. విజయవ్యూహంలో, మేము తెలంగాణ మరియు ఆంధ్రప్రదేశ్‌లోని నియోజకవర్గాల కోసం ఈ వ్యవస్థలను నిర్మిస్తాము.",
      "title_hi": "तेलुगु निर्वाचन क्षेत्रों को जीतने के लिए बूथ-स्तरीय रणनीति गाइड",
      "excerpt_hi": "चुनाव बूथ दर बूथ जीते और हारे जाते हैं। बूथ प्रबंधन नज़दीकी मुकाबलों को कैसे तय करता है, इसका व्यावहारिक विश्लेषण।",
      "content_hi": "तेलुगु राज्यों में किसी भी अनुभवी अभियान प्रबंधक से पूछें कि चुनाव वास्तव में कहां जीते जाते हैं, और उत्तर हमेशा एक ही होता है: बूथ पर। एक निर्वाचन क्षेत्र एक बड़ी लड़ाई नहीं है — यह सैकड़ों छोटी लड़ाइयां हैं।\n\nबूथ-प्रथम निष्पादन का अर्थ है प्रत्येक मतदान बूथ को जवाबदेही की इकाई के रूप में मानना। विजयव्यूहम में, हम तेलंगाना और आंध्र प्रदेश के निर्वाचन क्षेत्रों के लिए ये प्रणालियां बनाते हैं।",
      "meta_title": "Booth-Level Strategy Guide for Winning Telugu Constituencies | Vijayavyuham",
      "meta_description": "A practical guide to booth management, local accountability, and turnout planning for winning close races in Telangana and Andhra Pradesh constituencies.",
      "keywords": "booth management Telangana, booth level strategy Andhra Pradesh, election field operations, turnout planning, political consultancy Telugu states",
      "is_published": 1,
      "published_at": "2025-11-18 09:00:00"
    },
    {
      "id": 3,
      "slug": "whatsapp-ivr-ai-video-modern-voter-outreach",
      "category": "Digital",
      "cover_image": null,
      "author": "Vijayavyuham Team",
      "title_en": "WhatsApp, IVR & AI Video: The New Toolkit for Voter Outreach",
      "excerpt_en": "The Telugu voter lives on WhatsApp. Learn how modern digital outreach — bulk messaging, IVR calls, and personalized AI video — is reshaping campaigns.",
      "content_en": "The single biggest shift in voter communication over the last five years has been the move to the smartphone — and in the Telugu states, that means WhatsApp. Voters who once received their political information from television and newspapers now get it, discuss it, and forward it on their phones every single day.\n\nModern campaigns meet voters where they already are. That starts with organized WhatsApp outreach: campaign updates, localized messages, event invitations, and rich media distributed through a structured volunteer network. It continues with IVR bulk calls — recorded voice messages in Telugu, Hindi, or English that reach lakhs of voters with measurable response tracking. And increasingly, it includes AI-personalized video: leader messages that address constituencies, communities, and supporters by name and locality, delivered at a scale that once seemed impossible.\n\nNone of these tools replace the ground game — they amplify it. A well-run digital program keeps a campaign present in a voter's daily life between doorstep visits, reinforces the core message, and creates opportunities for two-way engagement.\n\nAt Vijayavyuham, we plan and execute integrated digital outreach tuned specifically for Telugu audiences, so your message lands with the right person, in the right language, at the right moment.",
      "title_te": "వాట్సాప్, IVR & AI వీడియో: ఓటర్ ప్రచారానికి కొత్త సాధనాలు",
      "excerpt_te": "తెలుగు ఓటరు వాట్సాప్‌లో నివసిస్తారు. ఆధునిక డిజిటల్ ప్రచారం ప్రచారాలను ఎలా మారుస్తుందో తెలుసుకోండి.",
      "content_te": "గత ఐదేళ్లలో ఓటర్ల సమాచారంలో అతిపెద్ద మార్పు స్మార్ట్‌ఫోన్‌కు మారడం — తెలుగు రాష్ట్రాల్లో అంటే వాట్సాప్. ఆధునిక ప్రచారాలు ఓటర్లు ఇప్పటికే ఉన్న చోట కలుస్తాయి.\n\nవిజయవ్యూహంలో, మేము తెలుగు ప్రేక్షకుల కోసం ప్రత్యేకంగా రూపొందించిన సమగ్ర డిజిటల్ ప్రచారాన్ని ప్లాన్ చేసి అమలు చేస్తాము.",
      "title_hi": "व्हाट्सएप, IVR और AI वीडियो: मतदाता आउटरीच के लिए नया टूलकिट",
      "excerpt_hi": "तेलुगु मतदाता व्हाट्सएप पर रहता है। जानें कि आधुनिक डिजिटल आउटरीच अभियानों को कैसे नया रूप दे रहा है।",
      "content_hi": "पिछले पांच वर्षों में मतदाता संचार में सबसे बड़ा बदलाव स्मार्टफोन की ओर बढ़ना रहा है — और तेलुगु राज्यों में, इसका मतलब व्हाट्सएप है। आधुनिक अभियान मतदाताओं से वहीं मिलते हैं जहां वे पहले से हैं।\n\nविजयव्यूहम में, हम तेलुगु दर्शकों के लिए विशेष रूप से तैयार एकीकृत डिजिटल आउटरीच की योजना बनाते और निष्पादित करते हैं।",
      "meta_title": "WhatsApp, IVR & AI Video Voter Outreach in Telugu States | Vijayavyuham",
      "meta_description": "How WhatsApp bulk messaging, IVR calls, and AI-personalized video are reshaping political voter outreach in Telangana and Andhra Pradesh.",
      "keywords": "WhatsApp campaign Telangana, IVR bulk calls Andhra Pradesh, AI video messaging politics, digital voter outreach Telugu, Vijayavyuham",
      "is_published": 1,
      "published_at": "2025-11-25 09:00:00"
    }
  ]
} as const;
